const IMAGES = {
  LOGO: require('_assets/icons/logo.png'),
  ICON_BACK_BUTTON: require('_assets/icons/back_icon.png'),
  ICON_RIGHT_ARROW: require('_assets/icons/arrow_right.png'),
  ICON_PASSWORD_EYE: require('_assets/icons/password-eye.png'),
  ICON_PASSWORD_EYE_ACTIVE: require('_assets/icons/password-eye-active.png'),
  ICON_APPLE_BTN: require('_assets/icons/apple-continue-btn.png'),
  ICON_GOOGLE_BTN: require('_assets/icons/google-continue-btn.png'),
  ICON_FACEBOOK_BTN: require('_assets/icons/fb-continue-btn.png'),
  PROFILE_PLACEHOLDER_IMAGE: require('_assets/icons/placeholder_photo.png'),
  ICON_ACTIVE_PROFILE: require('_assets/icons/active_profile.png'),
  ICON_PROFILE: require('_assets/icons/profile.png'),
  ICON_ACTIVE_WINNERS: require('_assets/icons/active_winners.png'),
  ICON_WINNERS: require('_assets/icons/winners.png'),
  ICON_ACTIVE_NOTI: require('_assets/icons/active_noti.png'),
  ICON_NOTI: require('_assets/icons/noti.png'),
  ICON_ACTIVE_HOME: require('_assets/icons/active_home.png'),
  ICON_HOME: require('_assets/icons/home.png'),
  ICON_SMALL_TICKET: require('_assets/icons/ticket_small.png'),
  ICON_ACTIVE_COUPON: require('_assets/icons/active_coupon.png'),
  ICON_COUPON: require('_assets/icons/coupon.png'),
  IMAGE_TICKET_BACKGROUND: require('_assets/images/ticket_bg.png'),
};

const STRING = {
  Sign_in: 'Sign in',
  Sign_up: 'Sign up',
  agree_text: 'By continuing, you agree to Oranpo’s',
  privacy_text: 'Privacy Policy',
  terms_text: 'Terms & Conditions',
  Or: 'OR',
  placeholder_email: 'Enter email',
  placeholder_phone: 'Phone Number',
  placeholder_first_name: 'First name',
  placeholder_last_name: 'Last name',
  placeholder_password: 'Enter password',
  forgot_pass: 'Forgot password?',
  create_pass: 'Create password',
  confirm_pass: 'Confirm password',
  header_phone_number: 'Enter phone number',
  header_upload_photo: 'Upload your photo',
  phone_number_large_text: `It will be used only to notify you when you will won a prize. It won’t be sended to third-party companies.`,
  upload_photo_large_text_start: `All Oranpo winners will be posted inside of  `,
  winners: 'Winners',
  upload_photo_large_text_end: ` section of the app with their photo. By uploading your photo, you give permission to process personal data. `,
  tap_to_upload: 'Tap to upload photo',
  tap_to_replace: 'Tap to replace photo',
  home: 'Home',
  notification: 'Notifications',
  profile: 'Profile',
  skip: 'Skip',
  and: 'and',
  create_acc: 'Create account',
};

export {IMAGES, STRING};
